# Generated by Django 4.0.5 on 2022-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_heading', models.CharField(max_length=50)),
                ('article_title', models.CharField(max_length=50)),
                ('article_des', models.TextField()),
            ],
        ),
    ]
