# Generated by Django 4.0 on 2022-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_icon', models.CharField(max_length=100)),
                ('article_title', models.CharField(max_length=100)),
                ('article_des', models.TextField()),
            ],
        ),
    ]
