# Generated by Django 4.0.5 on 2022-07-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_heading', models.CharField(max_length=50)),
                ('cards_title', models.CharField(max_length=50)),
                ('cards_des', models.TextField()),
            ],
        ),
    ]
