# Generated by Django 4.0.5 on 2022-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards_cards_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='cards_link',
            field=models.CharField(default='https://www.google.com/', max_length=50),
        ),
    ]
