# Generated by Django 4.0.5 on 2022-07-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cards_cards_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='cards_link',
            field=models.CharField(default='/articles1.html', max_length=50),
        ),
    ]
